FROM python:3.10-slim-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard_page_generator/ dashboard_page_generator/
COPY data_source/ data/raw/
COPY docs/ data/docs/

CMD ["python", "-m", "dashboard_page_generator.start"]